version: "3.9"

services:

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db

  app:
    build: ./src
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    command: python server.py
    container_name: sanic_app
    depends_on:
      - db